import streamlit as st
import json
import os
import time
import numpy as np

# CONFIGURATION

FRAME_PATH = "outputs/latest_frame.jpg"
STATUS_PATH = "outputs/current_status.json"
EVENT_LOG_PATH = "outputs/logs/events.json"
STOP_FILE = "outputs/stop.flag"


# PAGE CONFIGURATION

st.set_page_config(
    page_title="DangerSense",
    page_icon="🛡️",
    layout="wide"
)


# HELPER FUNCTIONS

def load_status():
    """
    Read the current status generated by the CV engine.
    """

    if not os.path.exists(STATUS_PATH):
        return None

    try:

        with open(
            STATUS_PATH,
            "r"
        ) as file:

            return json.load(file)

    except (json.JSONDecodeError, FileNotFoundError):

        return None


def load_events():
    """
    Read confirmed events from the event log.
    """

    if not os.path.exists(EVENT_LOG_PATH):
        return []

    try:

        with open(
            EVENT_LOG_PATH,
            "r"
        ) as file:

            return json.load(file)

    except (json.JSONDecodeError, FileNotFoundError):

        return []


# HEADER

st.title("🛡️ DangerSense")

st.caption(
    "AI-Powered CCTV Safety Monitoring System"
)

# SYSTEM CONTROL

system_stopped = (
    st.session_state.get(
        "system_stopped",
        False
    )
    or
    os.path.exists(STOP_FILE)
)

st.subheader("System Control")


if st.button(
    "⛔ Stop DangerSense",
    type="primary"
):

    os.makedirs(
        "outputs",
        exist_ok=True
    )

    with open(
        STOP_FILE,
        "w"
    ) as file:

        file.write("STOP")


    st.session_state["system_stopped"] = True


# LOAD DATA

status_data = load_status()

events = load_events()


# MAIN DASHBOARD

camera_column, status_column = st.columns(
    [2, 1]
)


# LIVE CAMERA

with camera_column:

    st.subheader("📹 Live Camera")


    if system_stopped:

        # Create a completely black frame
        black_frame = np.zeros(
            (480, 640, 3),
            dtype=np.uint8
        )

        st.image(
            black_frame,
            width="stretch"
        )

        st.error(
            "⛔ DangerSense has been stopped."
        )


    elif os.path.exists(FRAME_PATH):

        st.image(
            FRAME_PATH,
            width="stretch"
        )


    else:

        st.warning(
            "Waiting for camera feed..."
        )

# CURRENT STATUS

with status_column:

    st.subheader("Current Status")

    if status_data is None:

        st.info(
            "⏳ Starting DangerSense..."
        )

    else:

        risk_level = status_data.get(
            "risk_level",
            "UNKNOWN"
        )

        event_name = status_data.get(
            "event",
            "UNKNOWN"
        )

        reason = status_data.get(
            "reason",
            "No information available."
        )


        # Status indicator

        if risk_level == "CRITICAL":

            st.error(
                "🔴 CRITICAL"
            )

        elif risk_level == "HIGH":

            st.warning(
                "🟠 HIGH RISK"
            )

        elif risk_level == "MEDIUM":

            st.warning(
                "🟡 MEDIUM RISK"
            )

        elif risk_level == "SAFE":

            st.success(
                "🟢 SAFE"
            )

        else:

            st.info(
                "🔵 MONITORING"
            )


        st.write(
            f"**Event:** {event_name}"
        )

        st.write(
            f"**Risk Level:** {risk_level}"
        )

        st.write(
            f"**Reason:** {reason}"
        )


# EVENT HISTORY

st.divider()

st.subheader("📋 Confirmed Incident History")


if events:

    recent_events = events[-10:]

    for event in reversed(recent_events):

        risk_level = event.get(
            "risk_level",
            "UNKNOWN"
        )

        event_name = event.get(
            "event",
            "UNKNOWN"
        )

        timestamp = event.get(
            "timestamp",
            "Unknown time"
        )

        reason = event.get(
            "reason",
            ""
        )


        # Select indicator
        if risk_level == "CRITICAL":

            icon = "🔴"

        elif risk_level == "HIGH":

            icon = "🟠"

        elif risk_level == "MEDIUM":

            icon = "🟡"

        else:

            icon = "🟢"


        st.write(
            f"{icon} **{event_name}** "
            f"— {risk_level} "
            f"— {timestamp}"
        )

        st.caption(
            reason
        )

else:

    st.info(
        "No confirmed incidents yet."
    )


# AUTO REFRESH

time.sleep(2)

st.rerun()